name = input("Your name? ")
city = input("Your city? ")
favouriteFood = input("Your favourite food? ")
favouriteMusic = input("Your favourite music? ")
print("Your name is " + name + " and you live in " + city)
print("You're probably hungry for " + favouriteFood + " while listening to " + favouriteMusic)
